version: '3.4'

services:
  sampledev:
    image: docker-jenkins-integration
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8081:8081
      - 5001:5001
